- name: Wipe Rust Server
  hosts: "{{ target }}"
  tasks:
    - name: Delete world files and user data
      script: /ansible-rustserver/scripts/deltree-except.ps1 -path "C:\RustServer\server\server1_data" -exclude "\\cfg\\|\\cfg"
      register: out
    - debug: var=out
    - name: Copy configuration file template
      win_template:
        src: /ansible-rustserver/templates/server.cfg.j2
        dest: C:\RustServer\server\server1_data\cfg\server.cfg
    - name: Copy start command file template
      win_template:
        src: /ansible-rustserver/templates/start_rust_server.cmd.j2
        dest: C:\Users\dcadmin\Desktop\start_rust_server.cmd
